CahyoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from OAuth.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story_6.urls')),
    path('', include('WebService.urls')),
    path('', include('OAuth.urls')),
    path('auth/', include('social_django.urls', namespace='social'))
]

OAuth/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

Story_6/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('post/', postView, name='post'),
    path('', statusView, name='statusView'),
    path('status/', status_result, name='result'),
    path('delete/', delete_database, name='delete'),
    path('profile/', profile_view, name='profile'),
    # path('library/', libraryView, name='library'),
    # path('request/', library),
    path('library/', index, name='library'),
    path('delete', delete),
    path('getdata', getData),

]

WebService/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'subscribe'
urlpatterns = [
    path('subscribe/', subscribe, name='subscribe'),
    url(r'^ajax/validate_email/$', validate_email, name='validate_email'),
    url(r'^list_subscribers', getDataSubscribers, name='list_subscribers'),
    url(r'^unsubscribe', unsubscribe, name='unsubscribe'),

]

Story_6/models.py
from django.db import models

# Create your models here.
class statusModels(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, null=True)

Story_6/forms.py
from django import forms

class statusPage(forms.Form):
    status = forms.CharField(label="What's your status?", max_length=300, widget=forms.TextInput(attrs={'class': 'form-control'}))

Story_6/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import statusPage
from .models import statusModels
import requests

# Create your views here.
def statusView(request):
    response = {}
    html = 'Story_6.html'
    response['form'] = statusPage
    result = statusModels.objects.all().order_by('date')
    response['result'] = result
    return render(request, html, response)


def status_result(request):
    result = statusModels.objects.all().order_by('date')
    response = {'result': result}
    html = 'Story_6.html'
    return render(request, html, response)

def delete_database(request):
    delete = statusModels.objects.all().delete()
    response = {'delete': delete, 'form': statusPage}
    html = 'Story_6.html'
    return render(request, html, response)

def profile_view(request):
    return render(request, "Profile.html")

def postView(request):
    response = {}
    stats = statusPage(request.POST or None)
    if (request.method == 'POST' and stats.is_valid()):
        response['status'] = request.POST['status']
        status_form = statusModels(status=response['status'])
        status_form.save()
    return HttpResponseRedirect('/')

# key = "quilting"
# def library(request):
#     books = list()
#     keywords = key
#     response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + keywords)
#     data = response.json()
#     for i in range(len(data['items'])):
#         books.append({
#             'id': data['items'][i]['id'],
#             'image': data['items'][i]['volumeInfo']['imageLinks']['thumbnail'],
#             'title': data['items'][i]['volumeInfo']['title'],
#             'author': data['items'][i]['volumeInfo']['authors'][0],
#         })
#     return JsonResponse({'books': books})
#
# def libraryView(request):
#     if request.method == "POST":
#         response = request.POST.get('keywords')
#         global key
#         key = response
#         return render(request, 'Library.html')
#     else:
#         return render(request, 'Library.html')

def index(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('login'))
    if request.method == 'POST':
        id = request.POST['id']
        if not 'book' in request.session.keys():
            request.session['book'] = [id]
            size = 1
        else:
            books = request.session['book']
            books.append(id)
            request.session['book'] = books
            size = len(books)
        return JsonResponse({'count': size, 'id': id})
    if 'book' in request.session.keys():
        listbookSession = request.session['book']
    else:
        listbookSession = []
    nama = request.session['name']
    return render(request, 'Library.html', {'count': len(listbookSession), 'nama': nama})


def getData(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('login'))
    url = "https://www.googleapis.com/books/v1/volumes?q=quilting"
    if request.method == "POST":
        query = request.POST['query']
        url = "https://www.googleapis.com/books/v1/volumes?q=" + query
    get = requests.get(url).json()
    hasil = get['items']
    newlist = []
    for items in hasil:
        dataId = items['id']
        if dataId in request.session['book']:
            bool = True
        else:
            bool = False
        newdict = {"title": items['volumeInfo']['title'], "authors": items['volumeInfo']['authors'],
                   "published": items['volumeInfo']['publishedDate'],
                   'id': items['id'], 'boolean': bool}
        newlist.append(newdict)
    return JsonResponse({'data': newlist})


def delete(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('login'))
    if request.method == 'POST':
        id = request.POST['id']
        books = request.session['book']
        books.remove(id)
        size = len(books)
        request.session['book'] = books
        return JsonResponse({'count': size})

Story_6/templates/Base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="landing page">
    <meta name="author" content="Ringgi Cahyo Dwiputra - 1706025005">
    <meta name="google-signin-client_id" content="632242128761-pba3bde883snq2ee4bmv8ck9sqm5p6gf.apps.googleusercontent.com">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch|Kosugi+Maru|PT+Sans+Narrow|Poor+Story|Quicksand|Quintessential|Rancho|Ribeye+Marrow|Roboto+Mono" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href={% static 'css/Styling.css' %}>

    {% block scripts %}
        <script type="text/javascript" src={% static "js/jquery-3.3.1.js" %}></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script type="text/javascript" src={% static "js/javascript.js" %}></script>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
    {% endblock %}

    <title>
        {% block title %}
            Facebook in Disguise.
        {% endblock title %}
    </title>
</head>

<body>
<div id="work-in-progress">
    <div class="work-spinner"></div>
</div>
    <header>
        <nav class="navbar navbar-inverse navbar-expand-lg">
            <div class="container-fluid">
                <div class="navbar-header">
                    <ul class="navbar-nav navbar-brand navbar-left">
                        <li><a style="font-size: 80px; font-family: 'Ribeye Marrow'; color: crimson" href={% url 'statusView' %}>R</a></li>
                    </ul>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item"><a style="color: gold" href={% url 'statusView' %}>Home <span class="glyphicon glyphicon-home"></span></a></li>
                        <li class="nav-item"><a style="color: gold" href={% url 'profile' %}>Profile <span class="glyphicon glyphicon-user"></span></a></li>
                        <li class="nav-item"><a style="color: gold" href={% url 'library' %}>Library <span class="glyphicon glyphicon-book"></span></a></li>
                        <li class="nav-item"><a style="color: gold" href={% url 'subscribe:subscribe' %}>Subscribe <span class="glyphicon glyphicon-check"></span></a></li>
                        <li class="nav-item"><a style="color: gold" href={% url 'login' %}>Sign In <span class="glyphicon glyphicon-log-in"></span></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <content>
        {% block content %}

        {% endblock content %}
    </content>

</body>
</html>

Story_6/templates/Library.html
{% extends 'Base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        Perpusat in Disguise
    {% endblock %}

    {% block scripts %}
        {{ block.super }}
        <script type="text/javascript" src="{% static '/js/oauth.js' %}"></script>
    {% endblock %}
</head>
{% block content %}
{#    {% csrf_token %}#}
{#    <br>#}
{#    <div class="container card">#}
{#        <div class="g-signin2" data-onsuccess="onSignIn" data-width="300" data-longtitle="true"></div>#}
{#        <br>#}
{#        <a href="{% url 'logout' %}" onclick="signOut();">Sign out</a>#}
{#    </div>#}
{#    <h1 id="me" style="margin-bottom: 3%">My Books</h1>#}
{#    <h3 id="fav" class="me1" style="margin-bottom: 3%">Total of My Favorite Books: 0</h3>#}
{#    <div class="row justify-content-center">#}
{#        <div class="col-12 col-md-10 col-lg-8">#}
{#            <form action="{% url 'library' %}" method="post">#}
{#                {% csrf_token %}#}
{#                <div class="card-body row no-gutters align-items-center">#}
{#                    <div class="col-auto">#}
{#                        <i class="fas fa-search h4 text-body"></i>#}
{#                    </div>#}
{#                    <div class="col">#}
{#                        <input class="form-control form-control-lg form-control-borderless" name="keywords"#}
{#                               type="search" placeholder="Search topics or keywords">#}
{#                    </div>#}
{#                    <div class="col-auto">#}
{#                        <button class="btn btn-lg btn-success" type="submit">Search</button>#}
{#                    </div>#}
{#                </div>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#    <body>#}
{#        <div class="table-responsive container-fluid">#}
{#            <table class="table table-hover table-bordered table-condensed" style="font-family: Papyrus; font-weight: bold; font-size: large">#}
{#                <thead class="thead-dark">#}
{#                    <th style="text-align: center;">Cover</th>#}
{#                    <th style="text-align: center;">Title</th>#}
{#                    <th style="text-align: center;">Author</th>#}
{#                    <th style="text-align: center;">Publisher</th>#}
{#                    <th style="text-align: center;">Add to Favorites</th>#}
{#                </thead>#}
{#                <tbody id="tableBody">#}
{##}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
{#    </body>#}
    {% csrf_token %}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
    <div>
        <h1> Hello {{ nama }}</h1>
        <h2>Collection:</h2>
        <ul>
            <li><h3 id="quilting">Quilting</h3></li>
            <li><h3 id="programming">Programming</h3></li>
            <li><h3 id="django">Django</h3></li>
            <li><h3 id="python">Python</h3></li>
        </ul>
    </div>
      <h1><span class="count">{{ count }}</span><img src="{% static 'images/Bookmarked.png' %}" style="width: 40px;"> </h1>
      <hr class="d-sm-none">
        <div class="signout"><a href="{% url 'logout' %}" onclick="signOut()">Sign out</a></div>
    </div>
    <div class="col-sm-8">
      <table class="table table-striped table-hover table-responsive-md table-secondary">
    <thead>
      <tr>
        <th>Title</th>
        <th>Authors</th>
        <th>Published</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
    </div>
  </div>
</div>
{% endblock %}
</html>

Story_6/templates/Profile.html
{% extends 'Base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        The story of mine
    {% endblock %}
</head>

{% block content %}
    <body>
    <div>
        <button class="btn-danger changethemebtn container" onclick="f()">Ubah Tema</button>
    </div>
    <div>
        <h2 id="me">The Writing of Me</h2>
    </div>
    <div class="me1">
        <p>The name is Ringgi Cahyo</p>
        <p>A man who will turn 20 next year</p>
        <p>A passionate boy who will InsyaAllah survive from his faculty</p>
        <p>Stand with the principle of "Done is better than perfect"</p>
    </div>

    <h2 style="font-family: Quintessential; text-align: center; margin-top: 3%">Want to know me more?</h2>
    <div class="container" id="accordion">
        <h3 class="accordion">Activities Nowadays</h3>
        <div style="font-family: Quicksand; background-color: azure;">
            <p>- 24/7 study at college</p>
            <p>- Do homeworks, yea, everytime</p>
            <p>- Bed rest because every people need to rest</p>
        </div>

        <h3 class="accordion">Organization Experiences</h3>
        <div style="font-family: Quicksand; background-color: azure;">
            <p>- Staf Pengembangan Sumber Daya Manusia BEM Fasilkom UI 2018</p>
            <p>- Ketua Sie. 9 OSIS SMAN 34 Jakarta Periode 2016</p>
        </div>

        <h3 class="accordion">Achievement</h3>
        <div style="font-family: Quicksand; background-color: azure;">
            <p>No achievement so far. Yet the best will come immediately.</p>
        </div>
    </div>
    </body>
{% endblock content %}
</html>

Story_6/templates/Story_6.html
{% extends 'Base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Story 6</title>
</head>
{% block content %}
    <body>
        <div>
            <button class="btn-danger changethemebtn container" onclick="f()">Ubah Tema</button>
        </div>
        <div class="form container">
            <h1 style="font-family: Rancho; text-align: center">Hello, Apa Kabar?</h1>
            <form action="/post/" method="POST" class="form-block">
                {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" class="btn-primary registerbtn" value="POST">
            </form>
        </div>
        <div class="container">
            <table class="table table-hover table-bordered table-condensed" style="font-family: Papyrus; font-weight: bold; font-size: large">
                <thead class="thead-dark">
                    <th style="text-align: center">Tanggal, Waktu</th>
                    <th style="text-align: center">Status</th>
                </thead>
                <tbody>
                    {% for status in result %}
                    <tr style="text-align: center">
                        <td> {{status.date}} </td>
                        <td> {{status.status}} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            <form action={% url 'delete' %}>
                <button type="submit" class="btn-danger registerbtn container">Delete All</button>
            </form>
        </div>
    </body>
{% endblock %}
</html>