CahyoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from OAuth.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story_6.urls')),
    path('', include('WebService.urls')),
    path('', include('OAuth.urls')),
    path('auth/', include('social_django.urls', namespace='social'))
]

OAuth/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

WebService/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'subscribe'
urlpatterns = [
    path('subscribe/', subscribe, name='subscribe'),
    url(r'^ajax/validate_email/$', validate_email, name='validate_email'),
    url(r'^list_subscribers', getDataSubscribers, name='list_subscribers'),
    url(r'^unsubscribe', unsubscribe, name='unsubscribe'),

]

WebService/models.py
from django.db import models
from django.contrib.auth.models import User

class subscriberModels(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=20)

WebService/forms.py
from django import forms

class subscriberPage(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Name'}))
    email = forms.EmailField(label='Email', max_length=50, required=True,
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control', 'placeholder': 'Enter Your E-mail'}))
    password = forms.CharField(label='Password', max_length=20, required=True,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Enter Your Password'}))

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     try:
    #         subscriberModels.objects.get(email=email)
    #     except subscriberModels.DoesNotExist:
    #         return email
    #     raise ValidationError('Email exists. Please use another email.')

WebService/views.py
import json
from django.shortcuts import render
from .models import subscriberModels
from .forms import subscriberPage
from django.http import HttpResponse
from django.http import JsonResponse


def subscribe(request):
    response = {}
    if request.method == 'POST':
        subscriber = subscriberPage(request.POST)
        if subscriber.is_valid():
            response['name'] = request.POST['name']
            response['email'] = request.POST['email']
            response['password'] = request.POST['password']
            subscriber_database = subscriberModels(name=request.POST['name'], email=request.POST['email'],
                                    password=request.POST['password'])
            subscriber_database.save()
            response['message'] = 'Data berhasil disimpan'
            response['success'] = True
            json_data = json.dumps(response)
            return HttpResponse(json_data, content_type='application/json')
        else:
            subscriber.clean()
            response['message'] = 'Data tidak berhasil disimpan'
            response['success'] = False
            json_data = json.dumps(response)
            return HttpResponse(json_data, content_type='application/json')
    else:
        subscriber = subscriberPage()
        return render(request, 'Subscribe.html', {'form': subscriber})


def validate_email(request):
    email = request.GET.get('email', None)
    data = {
        'is_taken': subscriberModels.objects.filter(email=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Email tersebut sudah pernah didaftarkan sebelumnya, silahkan daftar dengan email lain.'
    return JsonResponse(data)

def getDataSubscribers(request):
    subscribers = subscriberModels.objects.all()
    data = list()
    for i in subscribers:
        result = {'name': i.name, 'email': i.email}
        data.append(result)
    return JsonResponse(data, safe=False)

def unsubscribe(request):
    if request.method == "POST":
        email = request.POST['email']
        subscriberModels.objects.get(email=email).delete()
        json_data = json.dumps({'message': 'Berhasil unsubscribe!'})
        return HttpResponse(json_data, content_type='application/json')
    else:
        subscriber = subscriberPage()
        return render(request, 'Subscribe.html', {'form': subscriber})

WebService/templates/Subscribe.html
{% extends 'Base.html' %}
{% load staticfiles %}
<!DOCTYPE html>

{% block title %}
    Subscribe Me
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/webservice.js' %}"></script>
{% endblock %}

{% block content %}
    <body>
        <div class="form container" style="margin-top: 5%">
            <form method="POST" class="form-block" data-validate-email-url="{% url 'subscribe:validate_email' %}" id="subscribeMe" action="#">
                {% csrf_token %}
                <h1>Subscribe</h1>
                <p>Please fill this form to subscribe me and get to know about me more!</p>
                {{ form.as_p }}
                <p>By registering as my subscriber, you agree to my <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
                <div class="clearfix">
                    <input type="submit" class="btn registerbtn" value="Kirim">
                </div>
            </form>
        </div>
        <div class="table-responsive container-fluid">
            <table class="table table-hover table-bordered table-condensed" style="font-family: Papyrus; font-weight: bold; font-size: large">
                <thead class="thead-dark">
                    <th style="text-align: center;">Name</th>
                    <th style="text-align: center;">Email</th>
                    <th style="text-align: center;">Unsubscribe</th>
                </thead>
                <tbody id="tableSubscriber">

                </tbody>
            </table>
        </div>
    </body>
{% endblock %}

</html>